name: auto-merge-on-approval-on-pr-into-prod
on:
  pull_request_review:
    types: [submitted]

jobs:
  approved:
    name: "Check approved"
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: "Merge Pull Request"
        uses: "actions/github-script@v5"
        with:
          github-token: "${{ secrets.MERGE_ON_PROD_APPROVAL }}"
          script: |
            const repository = context.repo

            console.log(github.event.pull_request)
            await github.rest.pulls.merge({
              merge_method: "merge",
              owner: repository.owner,
              pull_number: github.event.pull_request.number,
              repo: repository.repo,
            })
